# Generated by Django 2.1.2 on 2018-11-12 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Licence', models.AutoField(primary_key=True, serialize=False, verbose_name='Licence Student')),
                ('Name1', models.CharField(max_length=50, verbose_name='Name')),
                ('Name2', models.CharField(blank=True, max_length=50)),
                ('Name3', models.CharField(blank=True, max_length=50)),
                ('LastName1', models.CharField(blank=True, max_length=50)),
                ('LastName2', models.CharField(blank=True, max_length=50)),
                ('BirthDate', models.DateField(verbose_name='Birth Name')),
                ('Email', models.EmailField(max_length=80)),
                ('Phone', models.PositiveIntegerField(blank=True, verbose_name='Contact Phone')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('LicenceType', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='studenttype',
            name='FKLicence',
        ),
        migrations.AlterField(
            model_name='assistance',
            name='FKLicence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AlterField(
            model_name='liststudents',
            name='FKLicence',
            field=models.ManyToManyField(to='users.User'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentType',
        ),
        migrations.AddField(
            model_name='user',
            name='FKLicenceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserType'),
        ),
        migrations.AddField(
            model_name='course',
            name='Teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
