# Generated by Django 2.1.2 on 2018-11-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181112_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=50, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
