# Generated by Django 2.1.2 on 2018-11-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181112_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FKLicenceType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserType'),
        ),
    ]
